//1: 不以DM结尾的VARCHAR
//2: 以DM结尾的VARCHAR
//3: Date
//4: Number

export const Type = {
  1: [
    {name: '等于(Equal)'},
    {name: '大于(Greater)'},
    {name: '大于等于(Greater_Equal)'},
    {name: '小于(Less)'},
    {name: '小于等于(Less_Equal)'},
    {name: '不等于(Not_Equal)'},
    {name: '在列表内(In)'},
    {name: '不在列表内(Not_In)'},
    {name: '在范围之间(Between_And)'},
    {name: '类似(Like)'},
    {name: '不类似(Not_Like)'},
    {name: '为空(Is_Null)'},
    {name: '不为空(Is_Not_Null)'}
  ],
  2: [
    {name: '等于(Equal)'},
    {name: '在列表内(In)'},
    {name: '不在列表内(Not_In)'},
    {name: '为空(Is_Null)'},
    {name: '不为空(Is_Not_Null)'}
  ],
  3: [
    {name: '等于(Equal)'},
    {name: '大于(Greater)'},
    {name: '大于等于(Greater_Equal)'},
    {name: '小于(Less)'},
    {name: '小于等于(Less_Equal)'},
    {name: '不等于(Not_Equal)'},
    {name: '在范围之间(Between_And)'},
    {name: '为空(Is_Null)'},
    {name: '不为空(Is_Not_Null)'}
  ],
  4: [
    {name: '等于(Equal)'},
    {name: '大于(Greater)'},
    {name: '大于等于(Greater_Equal)'},
    {name: '小于(Less)'},
    {name: '小于等于(Less_Equal)'},
    {name: '不等于(Not_Equal)'},
    {name: '在列表内(In)'},
    {name: '不在列表内(Not_In)'},
    {name: '在范围之间(Between_And)'},
    {name: '类似(Like)'},
    {name: '不类似(Not_Like)'},
    {name: '为空(Is_Null)'},
    {name: '不为空(Is_Not_Null)'}
  ]
};

export const data = [
  {
    name: '人员基本信息',
    attributes: [
      {name: "人员编码", type: 1},
      {name: "姓名拼音", type: 1},
      {name: "管理单位", type: 1},
      {name: "文化程度", type: 2},
      {name: "政治面貌", type: 2},
      {name: "宗教信仰", type: 2},
      {name: "地区属性", type: 1},
      {name: "婚姻状况", type: 2},
      {name: "婚变日期", type: 3},
      {name: "初婚日期", type: 3},
      {name: "社保状况", type: 1},
      {name: "健康状况", type: 2},
      {name: "职业", type: 2},
      {name: "工作单位", type: 1},
      {name: "联系电话", type: 1},
      {name: "父亲编码", type: 1},
      {name: "父亲姓名", type: 1},
      {name: "父亲证件类型", type: 2},
      {name: "父亲证件号码", type: 1},
      {name: "母亲编码", type: 1},
      {name: "母亲姓名", type: 1},
      {name: "母亲证件类型", type: 2},
      {name: "母亲证件号码", type: 1},
      {name: "配偶编码", type: 1},
      {name: "配偶姓名", type: 1},
      {name: "配偶证件类型", type: 2},
      {name: "配偶证件号码", type: 1},
      {name: "户口性质", type: 2},
      {name: "户口编号", type: 1},
      {name: "与户主关系", type: 2},
      {name: "户籍地详址", type: 1},
      {name: "迁移日期", type: 3},
      {name: "迁移类型", type: 2},
      {name: "居住性质", type: 2},
      {name: "现居地详址", type: 1},
      {name: "流动日期", type: 3},
      {name: "流动类型", type: 2},
      {name: "流动原因", type: 2},
      {name: "验证日期", type: 3},
      {name: "发证日期", type: 3},
      {name: "证件截至日期", type: 3},
      {name: "流动证编号", type: 1},
      {name: "本人领证日期", type: 3},
      {name: "子女领证日期", type: 3},
      {name: "退出日期", type: 3},
      {name: "退出原因", type: 2},
      {name: "奖励扶住日期", type: 3},
      {name: "填报发证日期", type: 3},
      {name: "建卡日期", type: 3},
      {name: "填表人", type: 1},
      {name: "是否育龄妇女", type: 2},
      {name: "是否独生子女", type: 2},
      {name: "户主编号", type: 1},
      {name: "分户标志", type: 1},
      {name: "备注", type: 1},
      {name: "姓名", type: 1},
      {name: "出生日期", type: 3},
      {name: "证件类型", type: 2},
      {name: "证件号码", type: 1},
      {name: "性别", type: 2},
      {name: "民族", type: 2},
      {name: "户籍地", type: 1},
      {name: "户籍地行政区划", type: 1},
      {name: "现居住地", type: 1},
      {name: "现居地行政区划", type: 1},
      {name: "登记单位", type: 1},
      {name: "登记名称", type: 1},
      {name: "报告人", type: 1},
      {name: "报告日期", type: 3},
      {name: "标志", type: 1},
      {name: "证明办理办理状态", type: 2},
      {name: "婚育证明号码", type: 1},
      {name: "是否领独生证", type: 2},
      {name: "当前避孕状况", type: 2},
      {name: "流出日期", type: 3},
      {name: "流入地登记日期", type: 3},
      {name: "流动状态", type: 2},
      {name: "是否退出系统", type: 2},
      {name: "退出系统原因", type: 2},
      {name: "男孩数", type: 4},
      {name: "女孩数", type: 4},
      {name: "照片路径", type: 1},
      {name: "离开日期", type: 3}
    ]
  },
  {
    name: '生养信息',
    attributes: [
      {name: '人员编码', type: 1},
      {name: '证件号码', type: 1},
      {name: '子女编码', type: 1},
      {name: '子女名称', type: 1},
      {name: '子女孩次', type: 1},
      {name: '子女性别', type: 2},
      {name: '政策属性', type: 2},
      {name: '违法原因', type: 2},
      {name: '子女身份号码', type: 1},
      {name: '子女出生日期', type: 3},
      {name: '子女户口性质', type: 2},
      {name: '血缘关系', type: 2},
      {name: '生养标志', type: 2},
      {name: '出生健康状况', type: 2},
      {name: '当前健康状况', type: 2},
      {name: '死亡日期', type: 3},
      {name: '领独生证日期', type: 3},
      {name: '服务证号', type: 1},
      {name: '发证日期', type: 3},
      {name: '生父编码', type: 1},
      {name: '生父姓名', type: 1},
      {name: '生父证件号码', type: 1},
      {name: '生母编码', type: 1},
      {name: '生母姓名', type: 1},
      {name: '生母证件号码', type: 1},
      {name: '抚养开始日期', type: 3},
      {name: '抚养结束日期', type: 3},
      {name: '抚养结束原因', type: 2},
      {name: '子女出生地行政区划', type: 1},
      {name: '子女出生地', type: 1},
      {name: '上报日期', type: 3},
      {name: '登记单位', type: 1},
      {name: '报告人', type: 1},
      {name: '报告日期', type: 3},
      {name: '标记', type: 1},
    ]
  },
  {
    name: '避孕状况',
    attributes: [
      {name: '人员编码', type: 1},
      {name: '证件号码', type: 1},
      {name: '避孕开始日期', type: 3},
      {name: '避孕实施机构', type: 2},
      {name: '避孕状况', type: 2},
      {name: '避孕终止日期', type: 3},
      {name: '终止避孕机构', type: 2},
      {name: '上报日期', type: 3},
      {name: '登记单位', type: 1},
      {name: '报告人', type: 1},
      {name: '报告日期', type: 3},
      {name: '标志', type: 1},
    ]
  }
];
